= Timespan
:author: Philip Michael Raab
:email: <peep@inane.co.za>
:revnumber: 0.2.0
:revdate: 2022-08-17
:experimental:
:icons: font
:source-highlighter: highlight.js
:sectnums: |,all|
:toc: auto

A `Timespan` is essentially a number of seconds that can be expressed in a few different ways. They can also be added or subtracted from *NOW* to get a _future_ or _past_ date and time. `Timespan` currently supports (to various degrees) three types/formats of time periods as well as three types/formats of expressing a datetime.

== Supported types / formats

This covers a basic overview of what a `Timespan` can convert between.

NOTE: Terminology various from one reference source to the next. Inane\Datetime uses the vague definitions bellow.

=== Time Periods

A length of time, like *5 minutes* which is the same as a *timespan 300*.

.Supported Time Periods
[opts="header"cols="1,1,2"]
|===
|Name |Type |Example
|timespan |seconds |`5400`
|duration |string |`2years 3d 7secs`
|DateInterval |class |`new DateInterval('PT300S')``
|===

=== Date and Time

A specific point in time, like *01 January 1970 02:00:00 AM SAST* which is the same as unix timestamp *0*.

.Supported Date Times
[opts="header"cols="1,1,2"]
|===
|Name |Type |Example
|timestamp |seconds |`236988000`
|formatted date |string |`06 July 1977 12:00:00 AM SAST`
|DateTime(Immutable) |class |`new DateTime('NOW')`
|===

== Examples

.example
[source,php]
----
// Create with current seconds since epoch
$epoch = new \Inane\Datetime\Timespan(time());
echo("Time since epoch: $epoch\n"); // 52y 32w 1d 6h 13i 1s (not what you got! lol.)

// Create from duration
$ts1 = \Inane\Datetime\Timespan::fromDuration('3 yrs 2w 2days 4 min');

// Automatic string conversion
echo("$ts1");                    // 3y 2w 2d 4i

echo($ts1->getTimespan());       // 96053496 (seconds)
// Timestamp uses now as it's point of reference
echo($ts1->getTimestamp());      // 1756477381 (added timespan to now)
echo($ts1->getTimestamp(false)); // 1564370389 (subtracted timespan from now)

// default format: Y-m-d H:i:s
echo($ts1->format());            // 2025-08-29 16:23:01
echo($ts1->format('', false) . "\n");   // 2019-07-29 05:19:49

// Another Timespan
$ts2 = new \Inane\Datetime\Timespan(8600);
echo("\tSymbol Format:");
echo("Default:\t" . $ts2->getDuration()); // 2hrs 23mins 20secs
echo("Char:\t\t" . $ts2->getDuration(\Inane\Datetime\Timespan::SYMBOL_CHAR)); // 2h 23i 20s (not the `i` for min char.)
echo("Abbreviated:\t" . $ts2->getDuration(\Inane\Datetime\Timespan::SYMBOL_ABBREVIATED)); // 2hrs 23mins 20secs
echo("Word:\t\t" . $ts2->getDuration(\Inane\Datetime\Timespan::SYMBOL_WORD) . "\n"); // 2hours 23minutes 20seconds

// Static conversion functions
$s1 = \Inane\Datetime\Timespan::dur2ts('1hr 30min');
echo("1hr 30min => $s1");

$d1 = \Inane\Datetime\Timespan::ts2dur(10800);
echo("10800 => $d1");
----
